/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface SimpleForm {
        /**
          * Form Action.
         */
        "action": string;
        /**
          * FormID.
         */
        "formId": string;
    }
    interface SimpleInput {
        /**
          * Label.
         */
        "label": string;
        /**
          * Name of the input.
         */
        "name": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSimpleFormElement extends Components.SimpleForm, HTMLStencilElement {
    }
    var HTMLSimpleFormElement: {
        prototype: HTMLSimpleFormElement;
        new (): HTMLSimpleFormElement;
    };
    interface HTMLSimpleInputElement extends Components.SimpleInput, HTMLStencilElement {
    }
    var HTMLSimpleInputElement: {
        prototype: HTMLSimpleInputElement;
        new (): HTMLSimpleInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "simple-form": HTMLSimpleFormElement;
        "simple-input": HTMLSimpleInputElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface SimpleForm {
        /**
          * Form Action.
         */
        "action"?: string;
        /**
          * FormID.
         */
        "formId": string;
    }
    interface SimpleInput {
        /**
          * Label.
         */
        "label"?: string;
        /**
          * Name of the input.
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "simple-form": SimpleForm;
        "simple-input": SimpleInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "simple-form": LocalJSX.SimpleForm & JSXBase.HTMLAttributes<HTMLSimpleFormElement>;
            "simple-input": LocalJSX.SimpleInput & JSXBase.HTMLAttributes<HTMLSimpleInputElement>;
        }
    }
}
